name: example-workflow
#adding a comment.
on: [push]
jobs:
  Dev-deploy:
    if: github.repository == 'bickyshaw98/conditional-workflow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats

  test-deploy:
    if: github.repository == 'bickyshaw98/conditional-workflow-'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats

  production-deploy:
    if: github.repository == 'bickyshaw98/conditional-workflow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
